import { ANATOMY_PARTS } from "@/constants/strings";

export const AnatomyString_en: { [key in ANATOMY_PARTS]: string } = {
  model: "Model",
  mandible_bone: "Mandible Bone",
  frontal_bone: "Frontal Bone",
  temporal_bone: "Temporal Bone",
  parietal_bone: "Parietal Bone",
  rib_bone: "Rib Bone",
  tibia_bone: "Tibia Bone",
  femur_bone: "Femur Bone",
  radius_bone: "Radius Bone",
  ulna_bone: "Ulna Bone",
  occipital_bone: "Occipital Bone",
  eye_hole: "Eye Hole",
  coronal_suture: "Coronal Suture",
  lambdoid_suture: "Lambdoid Suture",
  squamous_suture: "Squamous Suture",
  suture: "Suture",
  backal_bone: "Backal Bone",
  pelvis_misc_muscle: "Pelvis Misc Muscle",
  leg_misc_muscle: "Leg Misc Muscle",
  stomach_muscle: "Stomach Muscle",
  rectus_abdominus_muscle: "Rectus Abdominus Muscle",
  oblique_muscle: "Oblique Muscle",
  abdominal_tendon: "Abdominal Tendon",
  left_arm_muscle: "Left Arm Muscle",
  arm_misc_muscle: "Arm Misc Muscle",
  triceps_muscle: "Triceps Muscle",
  deltoid_muscle: "Deltoid Muscle",
  biceps_muscle: "Biceps Muscle",
  hand_misc_muscle: "Hand Misc Muscle",
  right_arm_muscle: "Right Arm Muscle",
  pectoralis_muscle: "Pectoralis Muscle",
  body_misc_muscle: "Body Misc Muscle",
  waist: "Waist",
  Body: "Body",
  sternum_bone: "Sternum Bone",
  spine_bone: "Spine Bone",
  pelvis_bone: "Pelvis Bone",
  Head: "Head",
  maxilla: "Maxilla",
  zygomatic: "Zygomatic",
  nasal_bone: "Nasal Bone",
  RightArm: "Right Arm",
  hand_bone: "Hand Bone",
  humerus_bone: "Humerus Bone",
  LeftArm: "Left Arm",
  RightLeg: "Right Leg",
  foot_bone: "Foot Bone",
  fibula_bone: "Fibula Bone",
  LeftLeg: "Left Leg",
  face_muscle: "Face Muscle",
  orbicularis_muscle: "Orbicularis Muscle",
  buccinator_muscle: "Buccinator Muscle",
  zygomaticus_major_muscle: "Zygomaticus Major Muscle",
  orbicularis_oculi_muscle: "Orbicularis Oculi Muscle",
  depressor_septi_muscle: "Depressor Septi Muscle",
  frontalis_muscle: "Frontalis Muscle",
  masseter_muscle: "Masseter Muscle",
  procerus_muscle: "Procerus Muscle",
  temporalis_muscle: "Temporalis Muscle",
  occipitalis_muscle: "Occipitalis Muscle",
  brain: "Brain",
  back_muscle: "Back Muscle",
  neck_misc_muscle: "Neck Misc Muscle",
  trapezius_muscle: "Trapezius Muscle",
  teres_major_muscle: "Teres Major Muscle",
  latissimus_dorsi_muscle: "Latissimus Dorsi Muscle",
  lower_back_misc_muscle: "Lower Back Misc Muscle",
  back_misc_muscle: "Back Misc Muscle",
  bone2: "Bone2",
  left_leg_muscle: "Left Leg Muscle",
  vastus_medialis_muscle: "Vastus Medialis Muscle",
  tibialis_anterior_muscle: "Tibialis Anterior Muscle",
  gastronemius_muscle: "Gastronemius Muscle",
  vastus_lateralis_muscle: "Vastus Lateralis Muscle",
  hamstring_muscle: "Hamstring Muscle",
  gluteus_muscle: "Gluteus Muscle",
  foot: "Foot",
  right_leg_muscle: "Right Leg Muscle",
};
/**
 * Retrieves the localised string for a given anatomy part.
 * @param key - The key to look up in the anatomy string object.
 * @returns The string associated with the key, or the key itself if not found.
 */
export const getAnatomyString = (key: ANATOMY_PARTS): string => {
  return AnatomyString_en[key] || key;
};

export type AnatomyLayers = "skin" | "muscle" | "skeleton" | "organs";
export const anatomyLayers: AnatomyLayers[] = [
  "skin",
  "muscle",
  "skeleton",
  "organs",
];
